Initial Development
SkylineCommunications/Skyline.DataMiner.CICD.Tools.MSTeamsWorkflowWebhookCard pull request #1
Opened 2024-07-22 11:56 UTC by janstaelensskyline

2024-07-22 14:46 UTC, MichielOda requested changes

2024-07-22 14:46 UTC, MichielOda commented on CICD.Tools.MSTeamsWorkflowWebhookCard.LibTests/CicdCardTests.cs
> +        [TestMethod, Ignore]
SQ remark: Add a reason to the ignore

2024-07-23 08:48 UTC, janstaelensskyline commented on CICD.Tools.MSTeamsWorkflowWebhookCard.LibTests/CicdCardTests.cs
> +        [TestMethod, Ignore]
Done

2024-07-23 09:42 UTC, MichielOda approved these changes

2024-07-23 14:09 UTC, merged